# Generated by Django 3.2.5 on 2021-07-21 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=200)),
                ('photos', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('dats', models.DateField(verbose_name=datetime.datetime(2021, 7, 21, 19, 12, 50, 169883))),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
